spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}

server:
  port: ${PAYMENT_SERVICE_PORT}
  servlet:
    context-path: /payment

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

grpc:
  server:
    port: ${GRPC_PORT}

deploy:
  env: ${DEPLOY_ENV}

logging:
  level:
    com.aarogya.payment_service: DEBUG
    org.springframework.data.mongodb: INFO
    com.razorpay: INFO

razorpay:
  key:
    id: ${RAZORPAY_KEY_ID}
    secret: ${RAZORPAY_KEY_SECRET}
  webhook:
    secret: ${RAZORPAY_WEBHOOK_SECRET}