package com.aarogya.doctor_service.enums;

public enum RatingTag {
    EXCELLENT_DIAGNOSIS,
    GREAT_BEDSIDE_MANNER,
    GOOD_LISTENER,
    THOROUGH_EXPLANATION,
    MINIMAL_WAIT_TIME,
    CLEAN_FACILITY,
    FRIENDLY_STAFF,
    EASY_APPOINTMENT,
    EFFECTIVE_TREATMENT,
    FOLLOW_UP_CARE,
    TELEMEDICINE_EXCELLENCE,
    EMERGENCY_CARE
}
