spring:
  application:
    name: appointment-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: password
      database: aarogyadb
      authentication-database: admin
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_URL}
  cache:
    type: redis

server:
  port: ${APPOINTMENT_SERVICE_PORT}
  servlet:
    context-path: /appointment

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

grpc:
  server:
    port: ${GRPC_PORT}

deploy:
  env: ${DEPLOY_ENV}

logging:
  level:
    com.aarogya.appointment_service: INFO
    org.springframework.data.mongodb: INFO

