spring.application.name: ${SPRING_APPLICATION_NAME}
eureka.client.service-url.defaultZone: ${EUREKA_SERVER_URL}
server.port: ${SERVER_PORT}

jwt:
  secretKey: ${JWT_SECRET_KEY}

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2