spring.application.name: ${SPRING_APPLICATION_NAME}
eureka.client.service-url.defaultZone: ${EUREKA_SERVER_URL}
server.port: ${SERVER_PORT}
cors:
  origin: ${FRONTEND_URL}

jwt:
  secretKey: ${JWT_SECRET_KEY}


logging:
  level:
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.cloud.gateway.filter.factory: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG


spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2