external.rxnav.rxcui-url=${DRUG_RXCUI_API_URL}
external.rxnav.interaction-url=${DRUG_INTERACTIONS_API_URL}
PRIVATE_KEY_PATH=${SIGNATURE_PRIVATE_KEY_PATH}
PUBLIC_KEY_PATH=${SIGNATURE_PUBLIC_KEY_PATH}

