spring:
  application:
    name: doctor-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m,recordStats

server:
  port: ${DOCTOR_SERVICE_PORT}
  servlet:
    context-path: /doctors

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

grpc:
  server:
    port: ${GRPC_PORT}

deploy:
  env: ${DEPLOY_ENV}

logging:
  level:
    com.aarogya.doctor_service: INFO
    org.springframework.data.mongodb: INFO


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,retries
  health:
    circuitbreakers:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always

async:
  core-pool-size: 10
  max-pool-size: 50
  queue-capacity: 100
  thread-name-prefix: doctor-async-

