spring:
  application:
    name: doctor-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: password
      database: aarogyadb
      authentication-database: admin
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_URL}

server:
  port: ${DOCTOR_SERVICE_PORT}
  servlet:
    context-path: /doctors

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

grpc:
  server:
    port: ${GRPC_PORT}

deploy:
  env: ${DEPLOY_ENV}

logging:
  level:
    com.aarogya.doctor_service: INFO
    org.springframework.data.mongodb: INFO


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,retries
  health:
    circuitbreakers:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always



