spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost


