package com.aarogya.email_service.enums;

public enum EmailType {
    OTP_VERIFICATION,
    PASSWORD_RESET,
    ACCOUNT_VERIFICATION,

    APPOINTMENT_REQUEST,
    APPOINTMENT_CONFIRMATION,
    APPOINTMENT_CANCELLATION,
    APPOINTMENT_REMINDER,
    EMERGENCY_APPOINTMENT,

    FOLLOW_UP_SCHEDULED,
    FOLLOW_UP_REMINDER,
    FOLLOW_UP_COMPLETED,

    WELCOME,
    NEWSLETTER,
    SYSTEM_NOTIFICATION
}
