spring:
  application:
    name: patient-management-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: password
      database: aarogyadb
      authentication-database: admin
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

server:
  port: ${PATIENT_MANAGEMENT_SERVICE_PORT}
  servlet:
    context-path: /patient

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

grpc:
  server:
    port: ${GRPC_PORT}

deploy:
  env: ${DEPLOY_ENV}

logging:
  level:
    com.aarogya.patient_management_service: INFO
    org.springframework.data.mongodb: INFO

resilience4j:
  ratelimiter:
    instances:
      medicationsRateLimiter:
        limitForPeriod: 120
        limitRefreshPeriod: 60s
        timeoutDuration: 500ms
        registerHealthIndicator: true
        eventConsumerBufferSize: 60
      vitalsRateLimiter:
        limitForPeriod: 150
        limitRefreshPeriod: 60s
        timeoutDuration: 500ms
        registerHealthIndicator: true
        eventConsumerBufferSize: 75
      symptomsRateLimiter:
        limitForPeriod: 180
        limitRefreshPeriod: 60s
        timeoutDuration: 500ms
        registerHealthIndicator: true
        eventConsumerBufferSize: 90
      medicalHistoryRateLimiter:
        limitForPeriod: 120
        limitRefreshPeriod: 60s
        timeoutDuration: 500ms
        registerHealthIndicator: true
        eventConsumerBufferSize: 60
      allergiesRateLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 60s
        timeoutDuration: 500ms
        registerHealthIndicator: true
        eventConsumerBufferSize: 50
      healthGoalsRateLimiter:
        limitForPeriod: 150
        limitRefreshPeriod: 60s
        timeoutDuration: 500ms
        registerHealthIndicator: true
        eventConsumerBufferSize: 75
      emergencyContactsRateLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 60s
        timeoutDuration: 500ms
        registerHealthIndicator: true
        eventConsumerBufferSize: 50
      doctorNotesRateLimiter:
        limitForPeriod: 200
        limitRefreshPeriod: 60s
        timeoutDuration: 500ms
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
      diseaseHistoryRateLimiter:
        limitForPeriod: 150
        limitRefreshPeriod: 60s
        timeoutDuration: 500ms
        registerHealthIndicator: true
        eventConsumerBufferSize: 100