spring:
  application:
    name: lab-service
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_URL}
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: password
      database: aarogyadb
      authentication-database: admin
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

logging:
  level:
    com.aarogya.lab_service: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

lab:
  business-hours:
    start: 8
    end: 18
  max-tests-per-order: 10
  result-retention-days: 365

server:
  port: ${LAB_SERVICE_PORT}
  servlet:
    context-path: /lab

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

grpc:
  server:
    port: ${GRPC_PORT}

deploy:
  env: ${DEPLOY_ENV}


resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
    instances:
      labOrderController:
        baseConfig: default
      labResultController:
        baseConfig: default
      labTestController:
        baseConfig: default
      highRateEndpoints:
        limitForPeriod: 20
        limitRefreshPeriod: 1s
      lowRateEndpoints:
        limitForPeriod: 5
        limitRefreshPeriod: 1s