package com.aarogya.auth_service.documents.enums;

public enum Specialization {
    CARDIOLOGY,
    DERMATOLOGY,
    NEUROLOGY,
    PEDIATRICS,
    ONCOLOGY,
    ORTHOPEDICS,
    GYNECOLOGY,
    RADIOLOGY,
    PSYCHIATRY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    OPHTHALMOLOGY,
    ENT, // Ear, Nose, and Throat
    ANESTHESIOLOGY,
    UROLOGY,
    PULMONOLOGY,
    NEPHROLOGY,
    RHEUMATOLOGY,
    GENERAL_SURGERY,
    INTERNAL_MEDICINE,
    INFECTIOUS_DISEASE,
    PATHOLOGY,
    PLASTIC_SURGERY,
    DENTISTRY,
    SPORTS_MEDICINE,
    EMERGENCY_MEDICINE,
    FAMILY_MEDICINE,
    HEMATOLOGY,
    IMMUNOLOGY
}
